---
- name: Install rustup & cargo
  vars:
    rustup_configure_shell: false
    rustup_cargo_crates: [cargo-watch, wasm-pack]
  include_role:
    name: hurricanehrndz.rustup

- name: Install python
  community.general.homebrew:
    name:
      - python@3.9
      - python@3.11

- name: Install node
  community.general.homebrew:
    name:
      - fnm
