return {
  {
    'williamboman/mason.nvim',
    opts = {
      ensure_installed = {
        'arduino-language-server',
        'blue',
        'clangd',
        'css-lsp',
        'cssmodules-language-server',
        'eslint_d',
        'flake8',
        'gopls',
        'html-lsp',
        'json-lsp',
        'lua-language-server',
        'prettier',
        'pyright',
        'ruff-lsp',
        'shellcheck',
        'shfmt',
        'stylelint-lsp',
        'stylua',
        'svelte-language-server',
        'typescript-language-server',
        'vue-language-server',
      },
    },
  },
}
