- name: Install Linuxbrew
  include_role:
    name: markosamuli.linuxbrew
  vars:
    linuxbrew_use_installer: true
    linuxbrew_init_shell: false

- name: Install essentials
  become: true
  loop:
    - build-essential
    - coreutils
    - curl
    - wget
    - tree
    - xclip
    - zsh
    - unzip
    - make
  apt:
    name: "{{ item }}"
    state: present
