---
- name: Install OSX command line tools
  include_role:
    name: elliotweiser.osx-command-line-tools

- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Install essentials
  become: true
  loop:
    - coreutils
    - curl
    - wget
    - tree
    - pbcopy
    - make
  community.general.homebrew:
    name: "{{ item }}"
    state: present
